<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerENQ2xYU\srcDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerENQ2xYU/srcDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerENQ2xYU.legacy');

    return;
}

if (!\class_exists(srcDebugProjectContainer::class, false)) {
    \class_alias(\ContainerENQ2xYU\srcDebugProjectContainer::class, srcDebugProjectContainer::class, false);
}

return new \ContainerENQ2xYU\srcDebugProjectContainer(array(
    'container.build_hash' => 'ENQ2xYU',
    'container.build_id' => 'c135522d',
    'container.build_time' => 1516876684,
));
