<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerKAxT1og\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKAxT1og/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKAxT1og.legacy');
=======
if (\class_exists(\ContainerSx2noXL\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSx2noXL/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSx2noXL.legacy');
>>>>>>> 0bec796ad1cf710c43318c714b924e4e8e382155

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerKAxT1og\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKAxT1og\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KAxT1og',
    'container.build_id' => '8fdf64bd',
    'container.build_time' => 1516876654,
=======
    \class_alias(\ContainerSx2noXL\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSx2noXL\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Sx2noXL',
    'container.build_id' => 'e79b816a',
    'container.build_time' => 1516877256,
>>>>>>> 0bec796ad1cf710c43318c714b924e4e8e382155
));
