<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerUcMxGni\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUcMxGni/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUcMxGni.legacy');
=======
<<<<<<< HEAD
if (\class_exists(\ContainerQ1EBVyN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ1EBVyN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQ1EBVyN.legacy');
=======
if (\class_exists(\ContainerXEgenbr\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEgenbr/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXEgenbr.legacy');
>>>>>>> c75da957463b412500a8d1755d1cebac634c1262
>>>>>>> c5261bf5e8683a623da9556f00dc23f5eabb4f21

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerUcMxGni\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUcMxGni\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UcMxGni',
    'container.build_id' => 'a5688726',
    'container.build_time' => 1516871315,
=======
<<<<<<< HEAD
    \class_alias(\ContainerQ1EBVyN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQ1EBVyN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Q1EBVyN',
    'container.build_id' => '94004b90',
    'container.build_time' => 1516870619,
=======
    \class_alias(\ContainerXEgenbr\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXEgenbr\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XEgenbr',
<<<<<<< HEAD
<<<<<<< HEAD
    'container.build_id' => 'ed9359ea',
    'container.build_time' => 1516871565,
=======
    'container.build_id' => '54e9c145',
    'container.build_time' => 1516872772,
>>>>>>> b3de45288a18251bb288d348e4dbddba62fcb8af
=======
    'container.build_id' => '0efa0745',
    'container.build_time' => 1516870455,
>>>>>>> c75da957463b412500a8d1755d1cebac634c1262
>>>>>>> c5261bf5e8683a623da9556f00dc23f5eabb4f21
));
