<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCOWl60l\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCOWl60l/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCOWl60l.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCOWl60l\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCOWl60l\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'COWl60l',
    'container.build_id' => '350387f9',
    'container.build_time' => 1516808137,
));
